### Get all Product Data
GET https://636a3f79b10125b78fd51599.mockapi.io/products

### Delete Products
DELETE https://636a3f79b10125b78fd51599.mockapi.io/products/24

### Put request
PUT https://636a3f79b10125b78fd51599.mockapi.io/products/24
Content-Type: application/json

{
    
}